import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import BlogMasonry from "../components/Blog/GetList/GetList";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Baeksikoo Network</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <figure>
          <img src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__340.jpg" />
          <figcaption>
            <p className={styles.date}>2022-03-16</p>
            <p className={styles.title}>녹조 현상의 원인과 대책</p>
            <p className={styles.description}>녹조현상과 그에따른 피해</p>
            <p className={styles.tag}>#논문_리딩</p>
          </figcaption>
        </figure> */}
      <main className={styles.main}>
        <BlogMasonry />
      </main>
      <footer className={styles.footer}>
        <p>Copyright 2022. Baeksikoo All rights reserved.</p>
      </footer>
    </div>
  );
};

export default Home;
